
channels:
  - bioconda
  - cyclus
  - conda-forge
  - r
dependencies:
 - fastqc
 - picard = 2.9.2
 - bwa
 - samtools
 - pyvcf
 - java-jdk
 - r-ggplot2
 - r-reshape
 - r-gplots
 - r-gsalib
 - pysam
 - bedtools
 - varscan
